In [1]:
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt
import math
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal

In [2]:
#旋转因子
def Wnm(N,M):
    return np.exp(-2j*np.pi/N*M)

In [3]:
#基2时间抽取4点FFT
#4-point Fast Fourier Transform by Decimation in Time
def FFT_4(x):
    x1=np.zeros(int(len(x)/2),dtype = complex)
    x2=np.zeros(int(len(x)/2),dtype = complex)
    X1=np.zeros(int(len(x)/2),dtype = complex)
    X2=np.zeros(int(len(x)/2),dtype = complex)
    X=np.zeros(int(len(x)),dtype = complex)
    for k in range(0,int(len(x)/2)):
        x1[k]=x[2*k]
        x2[k]=x[2*k+1]
        
    X1[0]=x1[0]+x1[1]*Wnm(4,0)
    X1[1]=x1[0]-x1[1]*Wnm(4,0)
    X2[0]=x2[0]+x2[1]*Wnm(4,0)
    X2[1]=x2[0]-x2[1]*Wnm(4,0)
    X[0]=X1[0]+X2[0]*Wnm(4,0)
    X[1]=X1[1]+X2[1]*Wnm(4,1)
    X[2]=X1[0]-X2[0]*Wnm(4,0)
    X[3]=X1[1]-X2[1]*Wnm(4,1)
    return X

#基2时间抽取8点FFT
def FFT_8(x):
    x1=np.zeros(int(len(x)/2),dtype = complex)
    x2=np.zeros(int(len(x)/2),dtype = complex)
    X1=np.zeros(int(len(x)/4),dtype = complex)
    X2=np.zeros(int(len(x)/4),dtype = complex)
    X3=np.zeros(int(len(x)/4),dtype = complex)
    X4=np.zeros(int(len(x)/4),dtype = complex)
    XX1=np.zeros(int(len(x)/2),dtype = complex)
    XX2=np.zeros(int(len(x)/2),dtype = complex)
    X=np.zeros(int(len(x)),dtype = complex)
    for k in range(0,int(len(x)/2)):
        x1[k]=x[2*k]
        x2[k]=x[2*k+1]
    #第一级
    X1[0]=x1[0]+x1[2]*Wnm(8,0)
    X1[1]=x1[0]-x1[2]*Wnm(8,0)
    X2[0]=x1[1]+x1[3]*Wnm(8,0)
    X2[1]=x1[1]-x1[3]*Wnm(8,0)
    X3[0]=x2[0]+x2[2]*Wnm(8,0)
    X3[1]=x2[0]-x2[2]*Wnm(8,0)
    X4[0]=x2[1]+x2[3]*Wnm(8,0)
    X4[1]=x2[1]-x2[3]*Wnm(8,0)
    
    #第二级
    XX1[0]=X1[0]+X2[0]*Wnm(8,0)
    XX1[1]=X1[1]+X2[1]*Wnm(8,2)
    XX1[2]=X1[0]-X2[0]*Wnm(8,0)
    XX1[3]=X1[1]-X2[1]*Wnm(8,2)
    XX2[0]=X3[0]+X4[0]*Wnm(8,0)
    XX2[1]=X3[1]+X4[1]*Wnm(8,2)
    XX2[2]=X3[0]-X4[0]*Wnm(8,0)
    XX2[3]=X3[1]-X4[1]*Wnm(8,2)
    
    #第三级
    X[0]=XX1[0]+XX2[0]*Wnm(8,0)
    X[1]=XX1[1]+XX2[1]*Wnm(8,1)
    X[2]=XX1[2]+XX2[2]*Wnm(8,2)
    X[3]=XX1[3]+XX2[3]*Wnm(8,3)
    X[4]=XX1[0]-XX2[0]*Wnm(8,0)
    X[5]=XX1[1]-XX2[1]*Wnm(8,1)
    X[6]=XX1[2]-XX2[2]*Wnm(8,2)
    X[7]=XX1[3]-XX2[3]*Wnm(8,3)
    return X1,X2,X3,X4,XX1,XX2,X

In [4]:
x=[1,2,3,4]
FFT_4(x)

array([10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])

In [5]:
x=[1,1,1,1,0,0,0,0]
FFT_8(x)

(array([1.+0.j, 1.+0.j]),
 array([1.+0.j, 1.+0.j]),
 array([1.+0.j, 1.+0.j]),
 array([1.+0.j, 1.+0.j]),
 array([2.+0.j, 1.-1.j, 0.+0.j, 1.+1.j]),
 array([2.+0.j, 1.-1.j, 0.+0.j, 1.+1.j]),
 array([4.+0.j        , 1.-2.41421356j, 0.+0.j        , 1.-0.41421356j,
        0.+0.j        , 1.+0.41421356j, 0.+0.j        , 1.+2.41421356j]))

In [6]:
#IFFT快速算法: 8点IFFT
def IFFT_8(X):
    X=np.conjugate(X)
    X=FFT_8(X)
    X=np.conjugate(X)
    x=X/8
    return x

In [7]:
#IFFT快速算法:4点IFFT
def IFFT_4(X):
    x=np.zeros(int(len(X)),dtype = complex)
    X=np.conjugate(X)
    X=FFT_4(X)
    X=np.conjugate(X)
    x=X/4.0
    return x

In [8]:
X=[1+2j, 2+3j, 3+4j, 4+5j]
IFFT_4(X)

array([ 2.50000000e+00+3.5j, -5.55111512e-17-1.j , -5.00000000e-01-0.5j,
       -1.00000000e+00+0.j ])